CREATE TABLE SchemaVersion (
    Hash TEXT NOT NULL
);

CREATE TABLE Game (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UniqueReference TEXT NOT NULL,
    Host INT NULL,
	PuzzleId INT NULL,
    FOREIGN KEY(Host) REFERENCES Player(Id),
	FOREIGN KEY(PuzzleId) REFERENCES Puzzle(Id)
);

CREATE TABLE Player (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    GameId INTEGER NULL,
    FOREIGN KEY(GameId) REFERENCES Game(Id)
);

CREATE TABLE Puzzle (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	EncodedImage TEXT NOT NULL
);

CREATE TABLE Piece (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	PuzzleId INTEGER NOT NULL,
	Position INTEGER NOT NULL,
	EncodedImage TEXT NOT NULL,
	FOREIGN KEY (PuzzleId) REFERENCES Puzzle(Id)
);