CREATE TABLE Game (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UniqueReference TEXT NOT NULL,
    Host INT NULL,
    FOREIGN KEY(Host) REFERENCES Player(Id)
);

CREATE TABLE Player (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    GameId INTEGER NULL,
    FOREIGN KEY(GameId) REFERENCES Game(Id)
);