<nav class="site-nav">

<ul id="tm" class="CMSListMenuUL">
    <li class="nav-dropdown CMSListMenuLI">
      <a class="CMSListMenuLink" href="#">Solutions</a>
      <div class="nav-dropdown-panel">
        <div class="nav-dropdown-panel-content">
          <ul class="CMSListMenuUL">
            <li class="CMSListMenuLI">
              <a class="CMSListMenuLink" href="#">Architect</a>
            </li>
            <li class="CMSListMenuLI">
              <a class="CMSListMenuLink" href="#">Engineers</a>
            </li>
            <li class="CMSListMenuLI">
              <a class="CMSListMenuLink" href="#">Construction</a>
            </li>
            <li class="CMSListMenuLI">
              <a class="CMSListMenuLink" href="#">Consultants</a>
            </li>
          </ul>
        </div>
      </div>
    </li>
    <li class="nav-dropdown CMSListMenuHighlightedLI">
      <a class="CMSListMenuLinkHighlighted" href="#">Products</a>
      <div class="nav-dropdown-panel">
        <div class="nav-dropdown-panel-content">
          <ul class="CMSListMenuUL">
            <li class="CMSListMenuLI">
              <a class="CMSListMenuLink" href="#">PA</a>
            </li>
            <li class="CMSListMenuLI">
              <a class="CMSListMenuLink" href="#">Mobile</a>
            </li>
            <li class="CMSListMenuLI">
              <a class="CMSListMenuLink" href="#">Tech Info</a>
            </li>
          </ul>
        </div>
      </div>
    </li>
    <li class="CMSListMenuLI">
      <a class="CMSListMenuLink" href="#">Events</a>
    </li>
    <li class="nav-dropdown CMSListMenuLI">
      <a class="CMSListMenuLink" href="#">Services</a>
      <div class="nav-dropdown-panel">
        <div class="nav-dropdown-panel-content">
          <ul class="CMSListMenuUL">
            <li class="CMSListMenuLI">
              <a class="CMSListMenuLink" href="#">Learning</a>
            </li>
            <li class="CMSListMenuLI">
              <a class="CMSListMenuLink" href="#">Support and IMP</a>
            </li>
          </ul>
        </div>
      </div>
    </li>
    <li class="nav-dropdown CMSListMenuLI">
      <a class="CMSListMenuLink" href="#">Company</a>
      <div class="nav-dropdown-panel">
        <div class="nav-dropdown-panel-content">
          <ul class="CMSListMenuUL">
            <li class="CMSListMenuLI">
              <a class="CMSListMenuLink" href="#">News</a>
            </li>
            <li class="CMSListMenuLI">
              <a class="CMSListMenuLink" href="#">Careers</a>
            </li>
            <li class="CMSListMenuLI">
              <a class="CMSListMenuLink" href="#">Partners</a>
            </li>
            <li class="CMSListMenuLI">
              <a class="CMSListMenuLink" href="#">History</a>
            </li>
          </ul>
        </div>
      </div>
    </li>
    <li class="CMSListMenuLI">
      <a class="CMSListMenuLink" href="#">Resources</a>
    </li>
    <li class="CMSListMenuLI">
      <a class="CMSListMenuLink" href="#">Contact</a>
    </li>

  </ul>

  </nav>