<article class="col-md-3 col-md-pull-9 sidenav">
	<h1>Title of area</h1>
	<ul>
		<li><a href="#">Option 1 <i class="fa fa-arrow-circle-right"></i></a></li>
		<li><a href="#">Option 2 <i class="fa fa-arrow-circle-right"></i></a></li>
		<li><a href="#">Option 3 <i class="fa fa-arrow-circle-right"></i></a></li>
		<li><a href="#">Option 4 <i class="fa fa-arrow-circle-right"></i></a></li>
		<li><a href="#">Option 5 <i class="fa fa-arrow-circle-right"></i></a></li>
		<li><a href="#">Option 6 <i class="fa fa-arrow-circle-right"></i></a></li>
		<li><a href="#">Option 7 <i class="fa fa-arrow-circle-right"></i></a></li>
		<li><a href="#">Option 8 <i class="fa fa-arrow-circle-right"></i></a></li>
	</ul>
</article>